### PR TITLE
add support for ripgrep

### PR DESCRIPTION
**Pull request by stardiviner**

### CODE REVIEW

**Comment by stardiviner** [comment]
Any considering on this PR?

**Comment by dakrone** [comment]
+1, I just tried to do this yesterday and was disappointed to find I have to fall back to regular `rgrep` instead to use wgrep

**Comment by thierryvolpiatto** [comment]
Lee Hinman <notifications@github.com> writes:

> +1, I just tried to do this yesterday and was disappointed to find I
> have to fall back to regular rgrep instead to use wgrep

Note that ripgrep is fully supported with wgrep when used as backend for helm.

(setq helm-grep-ag-command "rg --color=always --smart-case --no-heading --line-number %s %s %s")

-- 
Thierry

**Comment by dakrone** [comment]
@thierryvolpiatto neat! I don't see how to enable wgrep for this though, does it work with that?

**Comment by stardiviner** [comment]
@thierryvolpiatto Which helm command is invoking this `helm-grep-ag-command`? I have not found `helm-grep-ag` command or `helm-ag`. And how to invoke wgrep in helm results?

**Comment by thierryvolpiatto** [comment]
stardiviner <notifications@github.com> writes:

> @thierryvolpiatto Which helm command is invoking this
> helm-grep-ag-command?

M-x helm-do-grep-ag

And from helm-find-files `M-g a`

> I have not found helm-grep-ag command or helm-ag. And how to invoke
> wgrep in helm results?

    (use-package wgrep-helm
      :config (setq wgrep-enable-key "\C-x\C-q"))

The default binding IIRC was `C-c C-p` (`wgrep-change-to-wgrep-mode`).

-- 
Thierry

**Comment by thierryvolpiatto** [comment]
Forget to mention that you have first to save your helm grep buffer with `C-x C-s` before being able to edit it with wgrep.

**Comment by stardiviner** [comment]
@thierryvolpiatto 
thanks

**Pull request closed without merging**
