### PR TITLE
Helm is no more storing fname/bufname in help-echo property, fix it.

### PR DESCRIPTION
**Pull request by thierryvolpiatto**
This PR fix issue #34

### CODE REVIEW

**Comment by mhayashi1120** [comment]
Thanks!

**Comment by lewang** [comment]
@thierryvolpiatto Is it possible to fix this for helm-moccur as well?

**Comment by thierryvolpiatto** [comment]
Le Wang <notifications@github.com> writes:

> @thierryvolpiatto Is it possible to fix this for helm-moccur as well?

helm-occur/moccur is already storing buffer-name in buffer-name
property, and AFAIK wgrep is using it.

You can save a helm-occur buffer and do M-x describe-text-properties in
it, you should see the buffer-name prop.

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Comment by lewang** [comment]
Had a closer look for why it didn't work, full path is needed, I opened a PR -- https://github.com/mhayashi1120/Emacs-wgrep/pull/37

**Comment by thierryvolpiatto** [comment]
Le Wang <notifications@github.com> writes:

> Had a closer look for why it didn't work,

What is not working ?
Can you clarify why you need buffer-file-name ?
We are treating buffers here not files.

> full path is needed,

Why ?

-- 
Thierry
Gpg Key fingerprint = 6CEC 7081 AB33 E251 4AB8  5FC2 28D1 7F53 59F2 9997

**Pull request merged**
